.TH chkcontents "1" "Feb 2002" "portage 1.8" 
.SH NAME
chkcontents \- manual page for the chkcontents program
.SH SYNOPSIS
.B chkcontents
\fI/path/to/CONTENTS\fR
.SH DESCRIPTION
The chkcontents command is a command-line program that takes the CONTENTS
file provided on the command line, compares the CONTENTS file against
the current filesystem (comparing MD5 sums and symlink targets), and lists
any discrepancies that it finds.  For example, "chkcontents 
/var/db/pkg/sys-devel/gcc-2.95.3-r5/CONTENTS" returns /usr/lib/libiberty.a as
having a different md5sum than what's listed in the CONTENTS file (because it
is overwritten by sys-devel/binutils).
.PP
.SH OPTIONS 
\fI--help\fR
.TP
Prints out help info.
.TP
.SH AUTHOR
Grant Goodyear <grant@gentoo.org>
.SH "SEE ALSO"
ebuild(1) emerge(5)
