.TH "G-CPAN.PL" "1" "Feb 2004" "Portage 2.0.51" "Portage"
.SH NAME
g-cpan.pl \- install CPAN-provided Perl modules using Gentoo's Portage
.SH SYNOPSIS
\fBg-cpan.pl\fR <\fImodule-name\fR>
.SH "DESCRIPTION"
.B g-cpan.pl
is a perl script that installs a CPAN module (including its
dependencies) using Gentoo's Portage.  It saves dependency information and 
stored files as if they were installed through a regular ebuild.

The first time you run \fBg-cpan.pl\fR, it will ask you to setup your CPAN
environment.  Most users can agree with the defaults asked.
.SH "EXAMPLES"
Here we install Jabber::RPC

# \fBg-cpan.pl Jabber::RPC\fR
.SH "AUTHORS"
J Robert Ray <jrray@gentoo.org> (g-cpan.pl)
.br
Sven Vermeulen <swift@gentoo.org> (manpage)
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "CVS HEADER"
$Header$
