.TH "PORTAGE" "5" "Jan 2004" "Portage 2.0.50" "Portage"
.SH NAME
portage \- the heart of Gentoo
.SH DESCRIPTION
The current portage code uses many different configuration files most of which 
are unknown to users and normal developers.  Here we will try to collect all 
the odds and ends so as to help users more effectively utilize portage.  This 
is a reference only for the things listed below and which do not already have 
a man page.

Note:
If you're looking for information on how to emerge something, please see 
\fBemerge\fR(1).
.SH SYNOPSIS
.TP
.BR /etc/
make.globals
.br
.BR make.conf (5)
.TP
.BR /etc/make.profile/
deprecated
.br
make.defaults
.br
packages
.br
packages.build
.br
use.defaults
.br
use.mask
.br
virtuals
.TP
.BR /etc/portage/
bashrc
.br
package.mask
.br
package.unmask
.br
package.keywords
.br
package.use
.br
mirrors
.br
categories
.br
use.mask
.TP
.BR /usr/portage/profiles/
arch.list
.br
categories
.br
package.mask
.br
thirdpartymirrors
.br
use.desc
.br
use.local.desc
.TP
.BR /var/cache/edb/
virtuals
.br
world
.SH SPECIFIC FILE DESCRIPTIONS
.TP
.B General Notes
In the following sections, some terminology may be foreign to you.  Please see 
the following manpages for explanations on each:

\fIDEPEND Atoms\fR: \fBebuild\fR(5)
.TP
.BR /etc/
.RS
.TP
.BR make.globals
The global default settings for Portage.  This comes from the portage package 
itself.  Override values here with make.conf.  See \fBmake.conf\fR(5).
.TP
.BR make.conf
The global custom settings for Portage.  See \fBmake.conf\fR(5).
.RE
.TP
.BR /etc/make.profile/
This is usually just a symlink to the correct profile in /usr/portage/profiles/.  
Since it is part of the portage tree, it may easily be updated/regenerated by 
running `emerge sync`.  It defines what a profile is (usually arch specific stuff).  
If you need a custom profile, then you should make your own /etc/make.profile/ 
directory and populate it.  However, if you just wish to override some settings, 
do NOT edit these files because they WILL be lost with the next `emerge sync`.  
See the section below on /etc/portage/ for overriding.
.RS
.TP
.BR deprecated
The existance of this file marks a profile as deprecated, meaning it is not 
supported by Gentoo anymore.  It contains the name of the profile users are 
encouraged to upgrade to.
.TP
.BR make.defaults
The profile default settings for Portage.  See \fBmake.conf\fR(5).
.TP
.BR packages
This file serves two purposes.  The first is to mask out specific packages/versions 
on a per-profile basis.  The second is to provide the list of packages that 
compose the special \fIsystem\fR class.

Format:
.br
\- comments begin with #
.br
\- one DEPEND atom per line of what to mask OUT
.br
\- packages to be added to the \fIsystem\fR class begin with a *

Example:
.br
# i am a comment !
.br
# only allow versions of glibc less than 2.3
.br
<sys-libs/glibc-2.3
.br
# add any version of bash to the \fIsystem\fR class
.br
*app-shells/bash
.br
# only allow versions of readline earlier than 4.2
.br
# and add it to the \fIsystem\fR class
.br
*<sys-libs/readline-4.2
.TP
.BR packages.build
A list of packages (one per line) that make up a stage1 tarball.  Really only 
useful for stage builders.
.TP
.BR use.defaults
Here we DON'T define the default USE flags, but the so called auto-USE flags.  
This rather unknown portage feature activates a USE flag if a specific package 
is installed and the flag was not explicitly deactivated.  This file contains the 
associations between USE flags and packages that trigger the auto-USE feature.  

In other words, if we never put 'sdl' or '-sdl' into our USE, but we have 
media-libs/libsdl emerged, then portage automagically sticks 'sdl' into our 
USE for us.

Format:
.br
\- comments begin with #
.br
\- one USE flag per line with a list of DEPEND atom bases

Example:
.br
.br
# media-libs/libsdl will activate 'sdl'
.br
sdl        media-libs/libsdl
.br
# activate tcltk only if we have both 
.br
# dev-lang/tcl and dev-lang/tk
.br
tcltk      dev-lang/tcl   dev-lang/tk
.TP
.BR use.mask
Some USE flags don't make sense on some archs (for example altivec on 
non-ppc or mmx on non-x86).  Here we list the masked ones.

Format:
.br
\- comments begin with #
.br
\- one USE flag per line
.TP
.BR virtuals
This controls what packages will provide a virtual by default.  For example, 
if a package needs to send e-mail, it will need virtual/mta.  In the absence 
of a package that provides virtual/mta (like qmail, sendmail, postfix, etc...), 
portage will look here to see what package to use.  In this case, Gentoo uses 
net-mail/ssmtp as the default (as defined in the virtuals file) because it's 
the package that does the very bare minimum to send e-mail.

Format:
.br
\- comments begin with #
.br
\- one virtual and DEPEND atom base pair per line

Example:
.br
# use net-mail/ssmtp as the default mta
.br
virtual/mta           net-mail/ssmtp
.br
# use app-dicts/aspell-en as the default dictionary
.br
virtual/aspell-dict   app-dicts/aspell-en
.RE
.TP
.BR /etc/portage/
.RS
.TP
.BR bashrc
If needed this file can be used to setup a different environment for ebuilds 
than the root environment.  Syntax is the same as any other bash scripts.
.TP
.BR package.mask
List of DEPEND atoms to mask.  Useful if specific versions of packages do not 
work well for you.  For example, you swear by the Nvidia drivers, but only 
versions earlier than 1.0.4496.  No problem!

Format:
.br
\- comments begin with #
.br
\- one DEPEND atom per line

Example:
.br
# mask out versions of the nvidia drivers
.br
# earlier than 1.0.4496
.br
>=media-video/nvidia-kernel-1.0.4496
.br
>=media-video/nvidia-glx-1.0.4496
.TP
.BR package.unmask
Just like package.mask above except here you list packages you want to unmask.  
Useful for overriding the global.mask file (see below).  Note that this does 
not override packages that are masked via KEYWORDS.
.TP
.BR package.keywords
Per package KEYWORDS.  Useful for mixing unstable packages in with a normally 
stable machine or vice versa.  This will allow you to override ACCEPT_KEYWORDS.

Format:
.br
\- comments begin with #
.br
\- one DEPEND atom per line followed by the KEYWORDS

Example:
.br
# always use unstable libgd
.br
media-libs/libgd ~x86
.br
# only use stable mplayer
.br
media-video/mplayer x86
.TP
.BR package.use
Per package USE flags.  Useful for tracking local USE flags or for enabling 
USE flags for only certain packages.  Perhaps you develop GTK and thus you 
want documentation for it, but you don't want documentation for QT.  Easy as 
pie my friend!

Format:
.br
\- comments begin with #
.br
\- one DEPEND atom per line followed by list of USE flags

Example:
.br
# turn on docs for GTK 2.x
.br
=x11-libs/gtk+-2* doc
.br
# disable mysql support for QT
.br
x11-libs/qt -mysql
.TP
.BR mirrors
Whenever portage encounters a mirror:// style URL it will look up the actual 
hosts here.  If the mirror set is not found here, it will check the global 
mirrors file at /usr/portage/profiles/thirdpartymirrors.  You may also set a 
special mirrortype called 'local'.  This list of mirrors will be checked before 
GENTOO_MIRRORS and be used even if the package has RESTRICT="nomirror".

Format:
.br
\- comments begin with #
.br
\- mirror type followed by a list of hosts

Example:
.br
# local private mirrors used only by my company
.br
local ftp://192.168.0.3/mirrors/gentoo http://192.168.0.4/distfiles

# people in japan would want to use the japanese mirror first
.br
sourceforge http://keihanna.dl.sourceforge.net/

# people in tawain would want to use the local gnu mirror first
.br
gnu ftp://ftp.nctu.edu.tw/UNIX/gnu/
.TP
.BR categories
A simple list of valid categories that may be used in /usr/portage, 
PORTDIR_OVERLAY, and PKGDIR (see \fBmake.conf\fR(5)).  This allows for custom 
categories to be created.

Format:
.br
\- one category per line

Example:
.br
app-hackers
.br
media-other
.TP
.BR use.mask
Just like the use.mask found in /etc/make.profile/.  See above for more 
information.
.RE
.TP
.BR /usr/portage/profiles/
Global Gentoo settings that are controlled by the developers.  To override 
these settings, you can use the files in /etc/portage/.
.RS
.TP
.BR arch.list
A list of all valid KEYWORDS.  This does not include modifiers.

Format:
.br
\- one KEYWORD per line

Example:
.br
x86
.br
ppc
.br
sparc
.TP
.BR categories
A simple list of valid categories that may be used in /usr/portage, 
PORTDIR_OVERLAY, and PKGDIR (see \fBmake.conf\fR(5)).

Format:
.br
\- one category per line

Example:
.br
app-admin
.br
dev-lang
.br
games-strategy
.br
sys-kernel
.TP
.BR package.mask
This contains a list of DEPEND atoms for packages that should not be installed 
in any profile.  Useful for adding the latest KDE betas and making sure no 
one accidently upgrades to them.  Also useful for quickly masking specific 
versions due to security issues.  ALWAYS include a comment explaining WHY the 
package has been masked and WHO is doing the masking.

Format:
.br
\- comments begin with #
.br
\- one DEPEND atom per line

Example:
.br
# masked for security reasons
.br
<sys-libs/zlib-1.1.4
.br
# <caleb@gentoo.org> (10 Sep 2003)
.br
# new kde betas
.br
=kde-base/kde-3.2.0_beta1
.br
=kde-base/kdeaccessibility-3.2.0_beta1
.TP
.BR thirdpartymirrors
Controls the mapping of mirror:// style URL's to actual lists of mirrors.  Keeps 
us from overloading a single server.

Format:
.br
\- comments begin with #
.br
\- mirror type followed by a list of hosts

Example:
.br
sourceforge http://aleron.dl.sourceforge.net/sourceforge http://unc.dl.sourceforge.net/sourceforge

gentoo http://distro.ibiblio.org/pub/linux/distributions/gentoo/distfiles/ ftp://ftp.gtlib.cc.gatech.edu/pub/gentoo/distfiles

kernel http://www.kernel.org/pub http://www.us.kernel.org/pub
.TP
.BR use.desc
All global USE flags must be listed here with a description of what they do.  

Format:
.br
\- comments begin with #
.br
\- use flag \- some description

Example:
.br
3dfx - Adds support for 3dfx video cards
.br
acl - Adds support for Access Control Lists
.br
doc - Adds extra documentation
.TP
.BR use.local.desc
All local USE flags must be listed here along with the package and a description.

Format:
.br
\- comments begin with #
.br
\- package:use flag \- description

Example:
.br
app-editors/nano:justify - Toggle the justify option
.br
dev-games/clanlib:clanJavaScript - Enables javascript support
.br
dev-libs/DirectFB:fusion - add Multi Application support
.br
games-emulation/xmess:net - Add network support
.RE
.TP
.BR /var/cache/edb/
.RS
.TP
.BR virtuals
Everytime a package is emerged that provides a virtual, that virtual to package 
mapping is recorded here.

Format:
.br
\- the virtual followed by the DEPEND atom bases that provide it

Example:
.br
virtual/inetd sys-apps/xinetd
.br
virtual/opengl media-video/nvidia-glx x11-base/xfree
.br
virtual/mta net-mail/qmail
.br
virtual/editor app-editors/vim app-editors/nano
.TP
.BR world
Everytime you emerge a package, the package that you requested is recorded 
here.  Then when you run `emerge world -up`, the list of packages is read from 
this file.  Note that this does not mean that the packages that were installed 
as dependencies are listed here.  For example, if you run `emerge mod_php` and 
you do not have apache already, then 'dev-php/mod_php' is recorded in the world 
file but 'net-www/apache' is not.  For more information, review \fBemerge\fR(1).

Format:
.br
\- one DEPEND atom base per line

Example:
.br
games-misc/fortune-mod-gentoo-dev
.br
dev-libs/uclibc
.br
app-cdr/cdemu
.RE
.SH AUTHORS
Marius Mauch <genone@gentoo.org>
.br
Mike Frysinger <vapier@gentoo.org>
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "SEE ALSO"
.BR emerge (1),
.BR ebuild (1),
.BR ebuild (5),
.BR make.conf (5)
.SH "CVS HEADER"
$Header$
